#!/bin/bash
# WSL2 Installation and Setup Script for APK Building

echo "=== Freevia APK Building Setup for WSL2 ==="
echo "Run these commands in PowerShell as Administrator:"
echo ""
echo "1. Install WSL2:"
echo "   wsl --install Ubuntu"
echo ""
echo "2. After WSL2 installs and reboots, run this in WSL:"
echo ""
echo "# Update system"
echo "sudo apt update && sudo apt upgrade -y"
echo ""
echo "# Install Python 3.13"
echo "sudo apt install software-properties-common -y"
echo "sudo add-apt-repository ppa:deadsnakes/ppa -y"
echo "sudo apt update"
echo "sudo apt install python3.13 python3.13-pip python3.13-dev -y"
echo ""
echo "# Install system dependencies for buildozer"
echo "sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev"
echo ""
echo "# Install Python packages"
echo "python3.13 -m pip install --user buildozer cython kivy[base]==2.3.1 requests pillow plyer"
echo "python3.13 -m pip install --user kivy-garden.mapview"
echo ""
echo "# Copy your project files to WSL (from Windows):"
echo "# cp -r /mnt/c/Users/Batuhan/Desktop/freevia/freevia-kivy ~/freevia-kivy"
echo "# cd ~/freevia-kivy"
echo ""
echo "# Build APK"
echo "# python3.13 -m buildozer android debug"
echo ""
echo "=== The APK will be created in bin/ directory ==="