name: Build iOS App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install system dependencies
      run: |
        brew install autoconf automake libtool pkg-config
        brew install libffi openssl
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython==3.0.10
        pip install kivy[base]==2.3.1 requests pillow plyer
        pip install kivy-garden.mapview
        
    - name: Install kivy-ios
      run: |
        pip install kivy-ios
        
    - name: Setup kivy-ios toolchain
      run: |
        toolchain build python3 kivy
        
    - name: Build iOS dependencies
      run: |
        toolchain build requests pillow plyer
        
    - name: Clean any previous builds
      run: |
        rm -rf .buildozer
        rm -rf ios-build
        
    - name: Install buildozer
      run: |
        pip install buildozer
        
    - name: Initialize buildozer for iOS
      run: |
        buildozer ios debug
      env:
        IOSROOT: ${{ github.workspace }}/.buildozer/ios
        
    - name: Upload iOS app artifact
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: freevia-ios-app
        path: |
          .buildozer/ios/platform/build-*/**/*.app
          .buildozer/ios/platform/build-*/**/*.ipa
        retention-days: 30
        
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ios-build-logs
        path: |
          .buildozer/ios/logs/
          *.log
        retention-days: 7